name: Tuck

options:
  usesTabs: false
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget: "26.0"

targets:
  Tuck:
    type: application
    platform: macOS
    deploymentTarget:
      macOS: "26.0"
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
    sources:
      - Tuck
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Tuck/Other/Tuck.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: "com.suffer77.Tuck"
        PRODUCT_NAME: Tuck
        SWIFT_VERSION: 5
        DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
        ENABLE_HARDENED_RUNTIME: true
        MACOSX_DEPLOYMENT_TARGET: "26.0"
        VERSIONING_SYSTEM: apple-generic
        CURRENT_PROJECT_VERSION: 1
schemes:
  Tuck:
    build:
      targets:
        Tuck: all
