name: Tuck

packages:
  Defaults:
    url: https://github.com/sindresorhus/Defaults
    from: 9.0.0
  Settings:
    url: https://github.com/sindresorhus/Settings
    from: 3.1.0
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern
    from: 1.1.0
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.4.0

options:
  usesTabs: false
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget: "13.0"

targets:
  Tuck:
    type: application
    platform: macOS
    deploymentTarget:
      macOS: "13.0"
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
    sources:
      - Tuck
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Tuck/Other/Tuck.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: "com.suffer77.Tuck"
        PRODUCT_NAME: Tuck
        SWIFT_VERSION: 5
        DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
        ENABLE_HARDENED_RUNTIME: true
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        VERSIONING_SYSTEM: apple-generic
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: Defaults
      - package: Settings
      - package: LaunchAtLogin
      - package: KeyboardShortcuts

schemes:
  Tuck:
    build:
      targets:
        Tuck: all
